# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Invoicer < Formula
  desc "Automate fraternity dues invoicing via Airtable and QuickBooks Online."
  homepage "https://github.com/OPPF-IHQ-IT/invoicer"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OPPF-IHQ-IT/invoicer/releases/download/v0.4.0/invoicer_darwin_amd64.tar.gz"
      sha256 "b02df97cbeb7b6694e7e1d72b6b2db33f129d466e5436f12c7ef98f5903933fb"

      define_method(:install) do
        bin.install "invoicer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OPPF-IHQ-IT/invoicer/releases/download/v0.4.0/invoicer_darwin_arm64.tar.gz"
      sha256 "8cec57492422faa90d6a055c41244949d801ff38d1a90205d5ad126f931d010c"

      define_method(:install) do
        bin.install "invoicer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OPPF-IHQ-IT/invoicer/releases/download/v0.4.0/invoicer_linux_amd64.tar.gz"
      sha256 "bf2fb426eb5f59a805b7131f4469768b4e1606a29db5c2c1d4773d1c6b68f003"
      define_method(:install) do
        bin.install "invoicer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OPPF-IHQ-IT/invoicer/releases/download/v0.4.0/invoicer_linux_arm64.tar.gz"
      sha256 "5817c7df8a6a3f921625d6eafd925f1dee5aaa9578c8d0f81a9878e8b4aa449c"
      define_method(:install) do
        bin.install "invoicer"
      end
    end
  end

  test do
    system "#{bin}/invoicer", "--help"
  end
end
