# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Invoicer < Formula
  desc "Automate fraternity dues invoicing via Airtable and QuickBooks Online."
  homepage "https://github.com/OPPF-IHQ-IT/invoicer"
  version "0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OPPF-IHQ-IT/invoicer/releases/download/v0.2.8/invoicer_darwin_amd64.tar.gz"
      sha256 "08547bbc1e9deaf2f1191d5dd2b183a3b38f0816b8c9730dc3e70b5adb9122bf"

      define_method(:install) do
        bin.install "invoicer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OPPF-IHQ-IT/invoicer/releases/download/v0.2.8/invoicer_darwin_arm64.tar.gz"
      sha256 "da123255eef60959e759a58de5e355daf4f4a8b251728911b91596b8d4ec2922"

      define_method(:install) do
        bin.install "invoicer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OPPF-IHQ-IT/invoicer/releases/download/v0.2.8/invoicer_linux_amd64.tar.gz"
      sha256 "dfcbff2713e58b4040d3d61220c2a042685ac925460fcd9b94df56ff312fbd78"
      define_method(:install) do
        bin.install "invoicer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OPPF-IHQ-IT/invoicer/releases/download/v0.2.8/invoicer_linux_arm64.tar.gz"
      sha256 "5a63f6c287eff9a2c29634ac3a9399fb403ac2e77b46abba2ef9862a60a91f95"
      define_method(:install) do
        bin.install "invoicer"
      end
    end
  end

  test do
    system "#{bin}/invoicer", "--help"
  end
end
